import type { VercelRequest, VercelResponse } from '@vercel/node';
import { HttpError, requireMethod, withErrorHandling } from '../_lib/http.js';
import { ADMIN_SESSION_COOKIE_NAME, verifySessionToken } from '../_lib/adminProxySession.js';

/**
 * ANY /api/newsroom-admin-proxy/<...path> — the trusted intermediary the
 * browser admin UI talks to instead of ever holding
 * `NEWSROOM_ADMIN_API_KEY` itself. Requires a valid session cookie (see
 * login.ts), then forwards the request server-to-server to the real
 * deployed Lambda admin API, attaching the real permanent key itself —
 * that attachment happens ONLY here, server-side, never in anything the
 * browser can inspect.
 *
 * Two separate secrets, two separate jobs: `NEWSROOM_ADMIN_SESSION_SECRET`
 * only verifies the session cookie's signature (never sent anywhere, never
 * proves anything to the Lambda); `NEWSROOM_ADMIN_API_KEY` only
 * authenticates the outbound call to the Lambda (never used to sign or
 * check anything about the cookie). A forged/expired cookie is rejected
 * before this function ever touches the Lambda credential at all.
 *
 * Transparent pass-through by design: same path shape (after this
 * function's own `/api/newsroom-admin-proxy` prefix is swapped for
 * `/api/newsroom`), same method, same body, same query string — the real
 * Lambda admin API contract (`api/newsroom/**`, unmodified by this file)
 * is preserved exactly, not reinvented. This file never imports or
 * duplicates any of that route/validation/business logic; it only relays
 * bytes and adds one header.
 *
 * Server-to-server, not a browser request — the Lambda's CORS
 * configuration (GET-only, one allowed origin) is irrelevant here, since
 * CORS is a browser-enforced mechanism that never applies to this call.
 */
export default async function handler(req: VercelRequest, res: VercelResponse) {
  await withErrorHandling(res, async () => {
    requireMethod(req, ['GET', 'POST', 'PATCH', 'DELETE']);

    const sessionSecret = process.env.NEWSROOM_ADMIN_SESSION_SECRET;
    if (!sessionSecret) {
      throw new HttpError(401, 'Newsroom admin proxy session signing is not configured in this environment');
    }
    const sessionToken = req.cookies[ADMIN_SESSION_COOKIE_NAME];
    if (!verifySessionToken(sessionToken, sessionSecret)) {
      throw new HttpError(401, 'Not authenticated');
    }

    const lambdaAdminKey = process.env.NEWSROOM_ADMIN_API_KEY;
    if (!lambdaAdminKey) {
      throw new HttpError(401, 'Newsroom admin API credential is not configured in this environment');
    }

    const targetBaseUrl = process.env.NEWSROOM_PUBLIC_API_BASE_URL;
    if (!targetBaseUrl) {
      throw new HttpError(401, 'Newsroom admin proxy target is not configured in this environment');
    }

    const pathSegments = req.query.path;
    const rawSegments = Array.isArray(pathSegments) ? pathSegments : pathSegments ? [pathSegments] : [];
    // Vercel's catch-all query delivery for a `[...path]` function is
    // split into an array in the common (Next.js) case, but this project's
    // framework preset is Vite, not Next.js, and that array-splitting
    // behavior is generated by Vercel's cloud routing layer rather than
    // anything inspectable locally — so this doesn't assume it happened.
    // Splitting every raw value on `/` here is a no-op when Vercel already
    // split it (each element already has no slashes) and self-correcting
    // when it didn't (a single slash-joined string arrives instead).
    const segments = rawSegments.flatMap((seg) => seg.split('/'));
    // Reject `.`/`..`/empty segments explicitly rather than relying on
    // fetch()'s own URL-normalization to collapse them harmlessly — a
    // request like path=[".."] would otherwise still resolve (URL parsing
    // collapses `/api/newsroom/..` up to the API Gateway's root), and while
    // this specific API Gateway currently exposes nothing else for that to
    // reach, this proxy shouldn't depend on that happening to be true.
    // Every real Newsroom admin path is a plain identifier/slug segment —
    // none legitimately contain `.` or `/`.
    if (segments.length === 0 || segments.some((seg) => seg === '.' || seg === '..' || seg === '')) {
      throw new HttpError(400, 'Invalid path segment');
    }
    const targetPath = `/api/newsroom/${segments.map(encodeURIComponent).join('/')}`;

    const queryString = new URLSearchParams();
    for (const [key, value] of Object.entries(req.query)) {
      if (key === 'path') continue;
      if (Array.isArray(value)) value.forEach((v) => queryString.append(key, v));
      else if (value !== undefined) queryString.append(key, value);
    }
    const qs = queryString.toString();
    const targetUrl = `${targetBaseUrl.replace(/\/+$/, '')}${targetPath}${qs ? `?${qs}` : ''}`;

    const upstreamRes = await fetch(targetUrl, {
      method: req.method,
      headers: {
        'Content-Type': 'application/json',
        'x-newsroom-admin-key': lambdaAdminKey,
      },
      body: req.method === 'GET' ? undefined : JSON.stringify(req.body ?? {}),
    });

    const contentType = upstreamRes.headers.get('Content-Type') ?? 'application/json';
    const text = await upstreamRes.text();
    res.status(upstreamRes.status);
    res.setHeader('Content-Type', contentType);
    // Never forward the upstream response verbatim without going through
    // this function's own response object — keeps this proxy the single
    // place that could redact something in the future, even though today
    // the real admin API's own responses are already safe (see
    // api/_lib/http.ts's withErrorHandling on the Lambda side).
    res.send(text);
  });
}
